name: Trigger Deploy via Comment

on:
  issue_comment:
    types:
      - created

jobs:
  trigger-deploy:
    if: github.event.comment.body == 'deploy' && github.event.issue.number == 1 && github.actor == 'alaycock'
    uses: ./.github/workflows/deploy.yml
